-- Database: test_restaurant

-- DROP DATABASE test_restaurant;

CREATE DATABASE test_restaurant
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

\c test_restaurant

-- Table: public.orders

-- DROP TABLE public.orders;

CREATE TABLE IF NOT EXISTS public.orders
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    table_id integer NOT NULL,
    dish_id integer NOT NULL,
    deleted boolean NOT NULL DEFAULT false,
    ready_time timestamp with time zone NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.orders
    OWNER to postgres;
-- Index: index_on_id

-- DROP INDEX public.index_on_id;

CREATE UNIQUE INDEX index_on_id
    ON public.orders USING btree
    (id ASC NULLS LAST)
    TABLESPACE pg_default;